In [2]:
import tensorflow as tf

In [4]:
tf.__version__

'2.9.1'

In [7]:
import keras as ks

In [8]:
ks.__version__

'2.9.0'

In [10]:
a=tf.constant(10.0)
b=tf.constant(10.0)
z=a+b
print(a+b)

tf.Tensor(20.0, shape=(), dtype=float32)


In [14]:
a=tf.Variable(12.0)
b=tf.Variable(10.0)
z=a+b
print(a+b)

tf.Tensor(22.0, shape=(), dtype=float32)


In [17]:
a=tf.Variable(initial_value=([[0,1,2,3],[4,5,6,7]]),shape=(2,4),dtype='int32',name='a')
print(a.numpy())
print(a.shape)      #length of dimensions
print(tf.rank(a))   #no. of dimensions

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)
tf.Tensor(2, shape=(), dtype=int32)


In [19]:
a=tf.Variable([1])  #only list will have the 1 dimension
print(a.numpy())
print(a.shape)      #length of dimensions
print(tf.rank(a))   #no. of dimensions

[1]
(1,)
tf.Tensor(1, shape=(), dtype=int32)


In [32]:
a=tf.Variable([[1],[2],[3],[4]])  
print(a.shape)      #length of dimensions
print(tf.rank(a)) #no. of dimensions
print(a)

(4, 1)
tf.Tensor(2, shape=(), dtype=int32)
<tf.Variable 'Variable:0' shape=(4, 1) dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]])>


In [24]:
a=tf.constant(50,shape=[6,2])
print(a.shape)      #length of dimensions
print(tf.rank(a))   #no. of dimensions
print(a)

(6, 2)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[50 50]
 [50 50]
 [50 50]
 [50 50]
 [50 50]
 [50 50]], shape=(6, 2), dtype=int32)


In [27]:
a=tf.convert_to_tensor(5.0,dtype=tf.float64)   #converting scaler value (5.0) into tensor value
print(a.shape)      #length of dimensions
print(tf.rank(a))   #no. of dimensions
print(a)
print(tf.shape(a)) 

()
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(5.0, shape=(), dtype=float64)
tf.Tensor([], shape=(0,), dtype=int32)


In [34]:
import numpy as np
b=([1],[2],[3],[4])

a=tf.convert_to_tensor(b,dtype=tf.float64)
print('\n')
print(tf.rank(a))   #no. of dimensions
print(a)
print(tf.shape(a)) 



tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[1.]
 [2.]
 [3.]
 [4.]], shape=(4, 1), dtype=float64)
tf.Tensor([4 1], shape=(2,), dtype=int32)
